swagger: '2.0'
info:
  version: bearer.v1
  title: Fixxbook.Bearer.Api.V1 AfterHours Branding API
  isOdataApi: false
  relativePath: ''
  discoveryPath: docs/bearer.v1
  _isAuthorizedAccess: true
host: sb2fixxbook.servicechannel.com:443
basePath: /api
schemes:
- https
security:
- oauth2: []
tags:
- name: Branding
paths:
  /branding/{subscriberId}:
    get:
      tags:
      - Branding
      operationId: GETv3_branding_{subscriberId}
      consumes: []
      produces:
      - application/json
      - text/json
      parameters:
      - name: subscriberId
        in: path
        required: true
        type: integer
        format: int32
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/System.Object'
      deprecated: false
      x-access: Any
definitions:
  System.Object:
    type: object
    properties: {}
securityDefinitions:
  oauth2:
    type: oauth2
    description: OAuth2 Authorization
    flow: accessCode
    authorizationUrl: https://sb2login.servicechannel.com/oauth/authorize
    tokenUrl: https://sb2login.servicechannel.com/oauth/token
    scopes: {}
