openapi: 3.2.0
info:
  version: '3'
  title: ServiceChannel API - v.3 Branding API
  description: The ServiceChannel API is a RESTful and stateless API.
servers:
- url: https://sb2api.servicechannel.com/v3
security:
- oauth2: []
tags:
- name: Branding
paths:
  /branding/{subscriberId}:
    get:
      tags:
      - Branding
      operationId: GETv3_branding_{subscriberId}
      parameters:
      - name: subscriberId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/System.Object'
            text/json:
              schema:
                $ref: '#/components/schemas/System.Object'
      deprecated: false
      x-access: Any
      summary: GETv3 branding {subscriber id}
      x-summary-source: derived
components:
  schemas:
    System.Object:
      type: object
      properties: {}
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          scopes: {}
          authorizationUrl: https://sb2login.servicechannel.com/oauth/authorize
          tokenUrl: https://sb2login.servicechannel.com/oauth/token
      description: OAuth2 Authorization
